require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

production = ENV["PRODUCTION"] == "1"

# Add this line, replacing 'Railway' with your actual project name if different
project 'Railway.xcodeproj'

target 'Railway' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],

    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RailwayTests' do
    inherit! :complete

  end

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,

    )
  end
end
