import { NetworkName } from "@railgun-community/shared-models";

export class SharedConstants {
  static BACKUP_DEFAULT_NETWORK_NAME = NetworkName.Ethereum;

  static SHOW_DEV_LOGS_REDUX = false;
  static USE_FAKE_PROOF_IN_DEV = false;
  static USE_COINGECKO_PRICES_FOR_TESTNETS_IN_DEV = false;

  static readonly MAX_LENGTH_WALLET_NAME = 18;

  static readonly POLL_GAS_PRICE_DELAY_RPC = 30000;

  static readonly POLL_MSEC_BASE_TOKEN_BALANCE = 90000;
  static readonly TIMEOUT_SEC_WATCH_TX_EXPIRATION = 24 * 60 * 60;
  static readonly TIMEOUT_MIN_WATCH_PENDING_PROMISE = 30;
  static readonly RETRY_DELAY_SEC_GET_TX_FROM_HASH = 15;

  static readonly GAS_PRICE_TIMEOUT = 20000;
  static readonly GAS_ESTIMATE_TIMEOUT = 60000;

  static readonly NETWORK_GAS_PRICE_CHANGE_THRESHOLD = 0.1;
  static readonly BROADCASTER_FEE_CHANGE_THRESHOLD = 0.05;

  static readonly NUM_FAILED_ATTEMPTS_FOR_DEVICE_WIPE = 20;

  static readonly DEFAULT_SLIPPAGE_PRIVATE_TXS = 0.05;
  static readonly DEFAULT_SLIPPAGE_PUBLIC_TXS = 0.01;
  static readonly ZERO_X_QUOTE_OUT_OF_DATE_BASIS_POINTS = 50n;

  static readonly PULL_BALANCES_INTERVAL = 5 * 60 * 1000;
  static readonly PULL_PRICES_INTERVAL = 300 * 1000;
  static readonly PULL_VAULTS_INTERVAL = 10 * 60 * 1000;

  static readonly MAX_TIMESTAMP_ARCHIVE_NODE_LOOP_LOOKUPS = 50;

  static readonly RECIPE_LOADING_VIEW_MIN_DISPLAY_TIME = 1000;

  static readonly SAVED_TRANSACTION_CURRENT_VERSION = "2.9";

  static readonly RAILGUN_CAT_COLLECTION_NFT_ADDRESS_LOWERCASE = "TODO";

  static readonly SELECTED_NETWORK = "SELECTED_NETWORK";
  static readonly TRANSACTIONS = "TRANSACTIONS";
  static readonly SAVED_ADDRESSES = "SAVED_ADDRESSES";
  static readonly AVAILABLE_WALLETS = "AVAILABLE_WALLETS";
  static readonly CACHED_BALANCES = "CACHED_BALANCES";
  static readonly CACHED_NFT_BALANCES = "CACHED_NFT_BALANCES";
  static readonly PIN_LOCKOUT_TIMESTAMP = "PIN_LOCKOUT_TIMESTAMP";
  static readonly NUM_ENTER_PIN_FAILED_ATTEMPTS =
    "NUM_ENTER_PIN_FAILED_ATTEMPTS";
  static readonly LAST_TRANSACTION_NONCE = "LAST_TRANSACTION_NONCE";
  static readonly SAVED_TRANSACTION_VERSION = "SAVED_TRANSACTION_VERSION";
  static readonly VIEWED_TEMP_NOTIFICATIONS = "VIEWED_TEMP_NOTIFICATIONS";
  static readonly NETWORK_STORED_SETTINGS = "NETWORK_STORED_SETTINGS";
  static readonly BLOCKED_BROADCASTERS = "BLOCKED_BROADCASTERS";
  static readonly NFT_IMAGE_CACHE = "NFT_IMAGE_CACHE";
  static readonly TRANSACTION_RECEIPT_DETAILS = "TRANSACTION_RECEIPT_DETAILS";
  static readonly COINGECKO_TOKEN_DETAILS = "COINGECKO_TOKEN_DETAILS";
  static readonly ERC20_DECIMALS = "ERC20_DECIMALS";
  static readonly LATEST_SYNCED_BLOCK_NUMBER = "LATEST_SYNCED_BLOCK_NUMBER";
  static readonly HAS_SEEN_APP_INTRO = "HAS_SEEN_APP_INTRO";
  static readonly HAS_SEEN_POI_SHIELD_DISCLAIMER =
    "HAS_SEEN_POI_SHIELD_DISCLAIMER";
  static readonly HAS_SEEN_OMITTED_PRIVATE_TOKENS =
    "HAS_SEEN_OMITTED_PRIVATE_TOKENS";
  static readonly HAS_SEEN_UNSHIELD_DESTINATION_DISCLAIMER =
    "HAS_SEEN_UNSHIELD_DESTINATION_DISCLAIMER";
  static readonly HAS_SEEN_RPC_SET_UP = "HAS_SEEN_RPC_SET_UP";
  static readonly POI_SHIELD_COUNTDOWN_TRANSACTIONS =
    "POI_SHIELD_COUNTDOWN_TRANSACTIONS";

  static readonly APP_SETTINGS_LOCALE = "APP_SETTINGS_LOCALE";
  static readonly APP_SETTINGS_CURRENCY_CODE = "APP_SETTINGS_CURRENCY_CODE";
  static readonly APP_SETTINGS_TXID_VERSION = "APP_SETTINGS_TXID_VERSION";

  static readonly MAINTENANCE_ERROR_TYPE = "MAINTENANCE";
  static readonly POLL_INVALIDATED_ERROR = "POLL_INVALIDATED_ERROR";
  static readonly ESTIMATING_GAS_FEE_TEXT = "Estimating...";

  static readonly LEGACY_EXPORT_WALLET_SALT =
    "910b9c87b738910a78c9d8338b200b23";

  static readonly TIMESTAMP_MISSING_VALUE = -1;
}
